apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - name: web
    port: 6379
    protocol: TCP
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    role: main
    app: redis
    #some: redis2
  annotations:
    co.elastic.metrics.redis/module: redis
    co.elastic.metrics.redis/hosts: '${data.host}:6379'
    co.elastic.metrics.redis/password: "${kubernetes.default.somesecret.value}"
    co.elastic.metrics.redis/period: 10s
    #co.elastic.metrics/password: "passpass3"
spec:
  containers:
    - name: redis
      image: redis
      command:
        - redis-server
        - "--requirepass 'passpass'"
      ports:
        - name: web
          containerPort: 6379
          protocol: TCP
